### ISSUE TITLE
请问这个如何加载到havoc呢

### ISSUE THREAD

**Issue by websecer** [Rvn0xsy/Havoc-Agent-Handler#2]
请问这个如何加载到havoc呢

**Comment by websecer** [comment]
修改了wss地址连接成功了，但是报错了。、
`2024-03-25 06:26:03,680 - INFO - [*] Successfully copied 'agent' to '/tmp/x11abj41'
Exception in thread Thread-3 (service_dispatch):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/admins/Havoc/Havoc-Agent-Handler/havoc/service.py", line 171, in service_dispatch
    self.RegisteredAgent.generate(data["Body"])
  File "/home/admins/Havoc/Havoc-Agent-Handler/handler.py", line 96, in generate
    process = subprocess.Popen(goreleaser_build_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=dest_dir, env=env_variables)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'goreleaser'
`

**Comment by whoami-privs** [comment]
just download the goreleaser
